server.port: 9090

spring:
  jpa:
    generate-ddl: false
    ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/pages
    username: pages
    password: pages
    driverClassName: com.mysql.jdbc.Driver
    
